Events handlers
KingsleyIbe/math-magicians pull request #3
Opened 2022-01-05 17:07 UTC by KingsleyIbe

# In this milestone, I implemented the following:

- Copied the files calculate.js and operate.js into a logic/ directory in my project.
-  Understand what each line of the code does.
- Imported the files in your Calculator component.
- Implemented the event handlers using the math logic from calculate.js and operate.js in my React component.
- Used state and props
-  Passed props to child components
-  Used lifecycle methods, lift state up.

2022-01-05 17:47 UTC, bimbolabuari requested changes
Hi @KingsleyIbe , 

You have done a good job so far 🚀  

## Highlights 🎉 

- Project has an `operate.js` file as required.
- Project has a `calculate.js` file as required.

There are some issues that you still need to work on to go to the next project but you are almost there! 🎉 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

--------


_Reviewed by  @bimbolabuari_

2022-01-05 17:47 UTC, bimbolabuari commented on src/Components/Calculator.js
> +            <button type="button" className="number" id="*" onClick={this.handleBtnClick}>&times;</button>
![image](https://user-images.githubusercontent.com/66112760/148263833-819aee36-7b95-408a-8ce5-df3a5e0afc61.png)

Kindly fix this error, as the web page goes blank when I use the '*' operator sign

2022-01-05 20:36 UTC, KingsleyIbe commented
Hi Abimbola,

Thanks for your feedback
Changes will be effected as recommended.

2022-01-05 21:10 UTC, D4nielJ approved these changes
## Hello @KingsleyIbe, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

![](https://i.giphy.com/media/U4DswrBiaz0p67ZweH/giphy.webp)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 06:25 UTC, KingsleyIbe commented
Hi Daniel,

Thank you for reviewing my project

2022-01-06 06:25 UTC, merged